# Copyright 2023 AssureMOSS
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Checkov JSON output parser

"""

import logging


def change_chart(key: str, value: str):
    pass



def parse_issues():
    pass

    # if CVK_K8S_12: change_chart('allowPrivileEscalation', 'false')



def json_parser(file_path: str):
    """
    Function to parse the JSON output generated by Checkov after 
    scanning Helm Chart.

    Args:
        file_path: A string representing the path to the JSON file.
    """

    logging.info('Running checkov JSON output parser')

    # parse scan.json

    print(file_path)

